party_at_your_door_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('singerqueue.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

singerqueue/urls.py
from django.urls import path
from .views import HomePageView, BookMePageView, SingerQueueView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('queue/', SingerQueueView.as_view(), name='queue'),
    path('bookme', BookMePageView.as_view(), name='bookme'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    room_id = models.CharField(default='000000', max_length=6)
    intermission = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return self.username

singerqueue/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


class Singer(models.Model):
    name = models.CharField(max_length=256)
    song_name = models.CharField(max_length=256)
    song_link = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home')


class ContactInfo(models.Model):
    social_type_choices = [
        ('', 'Please pick a social contact type'),
        ('tiktok', 'TikTok'),
        ('X', 'X'),
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
        ('phone_number', 'Phone Number'),
        ('email', 'Email'),


    ]

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20, blank=True)
    social_types = models.CharField(max_length=12, choices=social_type_choices, default='')
    social_contact = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('queue')

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'room_id', 'intermission')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'room_id', 'intermission')

singerqueue/forms.py
from django import forms
from .models import Singer, ContactInfo
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

User = get_user_model()


def validate_room_id(value):
    try:
        superuser = User.objects.get(is_superuser=True)
        if value.lower() != superuser.room_id.lower():
            raise ValidationError("Incorrect Room ID. Please try again.")
    except User.DoesNotExist:
        raise ValidationError("Room does not exist.")


class SingerForm(forms.ModelForm):
    class Meta:
        model = Singer
        fields = "__all__"


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactInfo
        fields = "__all__"
        widgets = {
            'social_types': forms.Select(attrs={
                'class': 'text-white text-center bg-p4 border-2 border-black focus:border-black focus:ring-black text-sm block w-full p-2.5'
            }),
            'room_id': forms.TextInput(attrs={
                'class': 'text-white text-center text-2xl placeholder-white placeholder:text-center placeholder:text-xl bg-p4 border-2 border-black focus:placeholder-opacity-0 focus:border-black focus:ring-black block w-full'
            })
        }

    room_id = forms.CharField(max_length=6, validators=[validate_room_id])

    def clean_room_id(self):
        return self.cleaned_data["room_id"]

accounts/views.py
from django.shortcuts import render

# Create your views here.

singerqueue/views.py
from django.views.generic import TemplateView, CreateView, ListView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .models import Singer, ContactInfo
from accounts.models import CustomUser
from .forms import SingerForm, ContactForm
from django.http import JsonResponse


class HomePageView(CreateView, FormView):
    guest_id = ''
    template_name = 'home.html'
    model = ContactInfo
    form_class = ContactForm
    success_url = reverse_lazy("queue")

    def form_valid(self, form):
        # This method is called when the form is valid
        return super().form_valid(form)  # This will redirect to success_url

    def form_invalid(self, form):
        # This method is called when the form is invalid
        return super().form_invalid(form)  # This will re-render the form with errors

    # Commented out error for login page, will come back to later

    # def form_invalid(self, form):
    #     # Check if the request is AJAX
    #     if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
    #         return JsonResponse({"errors": form.errors}, status=400)
    #     return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['guest_id'] = self.guest_id
        context['contacts'] = ContactInfo.objects.all()
        context['admin'] = CustomUser.objects.get(id=1)
        return context


class SingerQueueView(CreateView, ListView):
    template_name = 'singer_queue.html'
    model = Singer
    form_class = SingerForm
    context_object_name = 'singers'
    success_url = reverse_lazy("queue")

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['guest_id'] = self.guest_id
    #     context['singers'] = Singer.objects.all()
    #     context['admin'] = CustomUser.objects.get(id=1)
    #     return context


class BookMePageView(TemplateView):
    template_name = 'bookme.html'

templates/bookme.html
{% extends 'base.html' %}
{% load static %}

{# HEADER #}
{% block header %}



    <nav class="text-center text-g1">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-around mx-auto p-4">
            <a href="{% url 'home' %}" class="flex items-center rtl:space-x-reverse">
                <span class="dokdo-regular m-auto self-center text-3xl font-semibold whitespace-nowrap dark:text-white">WELCOME TO THE PARTY</span>
            </a>


{#            <p>{{ admin.room_id }}</p>#}
{#            {% for user in custom_user %}#}
{#                <p>{{ user.room_id }}</p>#}
{#            {% endfor %}#}


{#            <button data-collapse-toggle="navbar-default" type="button"#}
{#                    class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm rounded-lg md:hidden"#}
{#                    aria-controls="navbar-default" aria-expanded="false">#}
{#                <span class="sr-only">Open main menu</span>#}
{#                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"#}
{#                     viewBox="0 0 17 14">#}
{#                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"#}
{#                          d="M1 1h15M1 7h15M1 13h15"></path>#}
{#                </svg>#}
{#            </button>#}
{#            <div class="hidden w-full" id="navbar-default">#}
{#                <ul class="font-medium flex flex-col md:p-0 mt-4 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0">#}
{#                    <li>#}
{#                        <a href="{% url 'home' %}">Book Me</a>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
        </div>
    </nav>


{% endblock header %}

{% block enterid %}

{% endblock enterid %}

{# MAIN #}
{% block content %}

    <div class="mt-8 flex flex-col items-center">
        <section class="w-11/12 flex flex-col border-2 border-p4">
            <h2 class="dokdo-regular text-g1 text-3xl text-center mt-2">How to sign-up</h2>
            <ol type="1" class="text-white text-center text-sm m-2">
                <li>1. <span class="border-b-g1 border-b-2">Find your song</span> choice on <a href="https://www.youtube.com/" class="text-o1 underline">YouTube.</a></li>
                <li>2. <span class="border-b-g1 border-b-2">Copy the link</span> from the YouTube page.</li>
                <li>3. <span class="border-b-g1 border-b-2">Click ‘Add Name’</span>. Paste the song link.</li>
            </ol>
        </section>

        <div class="flex justify-center items-center w-full p-4">
          <!-- Image -->
          <img class="w-1/2 h-auto p-4" src="{% static 'images/partyatyourdoorimage_new.png' %}" alt="Party At Your Door">

          <!-- Sign-up Button -->
          <button data-modal-target="authentication-modal" data-modal-toggle="authentication-modal"
                  class="dokdo-regular h-auto w-auto border-2 border-g1 bg-p1 text-g1 p-4 mx-4" type="button">
            Sign Me Up!
          </button>
        </div>

        <div class="w-full flex flex-col items-center space-y-5">


            {#    Song Queue    #}
            <section
                    class="w-11/12 flex flex-col items-center justify-around border-2 border-green-400 bg-gradient-to-b from-p1 to-p2">

                <p class="dokdo-regular text-center p-4 text-2xl text-g1">SONG QUEUE</p>
                <div class="w-full flex flex-col bg-black mx-24 p-2 space-y-2">
                    <div class="flex justify-between text-o1 bg-black border-2 border-g1">
                        <span class="dokdo-regular basis-1/12">#</span>
                        <span class="dokdo-regular basis-1/3">Name</span>
                        <span class="dokdo-regular basis-1/2">Song Name</span>
                    </div>

                    {# queue of users place, name, song #}
                    <div class="h-32 overflow-y-auto flex flex-col space-y-2">
                        {% for singer in singers %}
                            {% if forloop.counter == 1 %}
                                <div class="flex justify-between bg-g1 text-p1">
                                    <div class="w-full flex justify-between">
                                        <span class="dokdo-regular basis-1/12">{{ forloop.counter }}</span>
                                        <p class="basis-1/3">{{ singer.name }}</p>
                                        <span class="basis-1/2 truncate">{{ singer.song_name }}</span>
                                    </div>
                                    {#                                    <button>EDIT</button>#}
                                </div>
                            {% else %}
                                <div class="flex justify-between bg-p1 text-o1">
                                    <div class="w-full flex justify-between">
                                        <span class="dokdo-regular basis-1/12">{{ forloop.counter }}</span>
                                        <p class="basis-1/3">{{ singer.name }}</p>
                                        <span class="basis-1/2">{{ singer.song_name }}</span>
                                    </div>
                                    {#                                    <button>EDIT</button>#}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>

            </section>



            <!-- Main modal -->
            <div id="authentication-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative p-4 w-full max-w-md max-h-full">
                    <!-- Modal content -->
                    <div class="relative bg-black border-2 border-p4 shadow">
                        <!-- Modal header -->
                        <div class="flex items-center justify-aroundx p-4 md:p-5 rounded-t">
                            <h3 class="dokdo-regular text-3xl font-semibold text-g1">
                                Sign Me Up!
                            </h3>


                            <button type="button" class="end-2.5 opacity-50 hover:opacity-100 focus:border-g1 bg-transparent text-xs ms-auto items-center" data-modal-hide="authentication-modal">
                                <svg class="text-g1 w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"></path>
                                </svg>
                                <span class="sr-only">Close modal</span>
                            </button>
                        </div>
                        <!-- Modal body -->
                        <div class="p-4 md:p-5">
                            <form method="post" class="space-y-4" action="#">
                                {% csrf_token %}
                                <div>
                                    <label for="id_name" class="dokdo-regular block text-xl mb-2 font-medium text-g1 dark:text-white">Name: <span class="dekko-regular text-o1 text-sm opacity-50">Get creative & pick your stage name</span></label>
                                    <input type="text" name="name" id="id_name" placeholder="_________________________________________________________________" class="text-white placeholder-white placeholder:text-center placeholder:-translate-y-1 bg-p4 border-2 border-black focus:border-black focus:ring-black text-sm block w-full p-2.5" required />
                                </div>
                                <div>
                                    <label for="id_song_name" class="dokdo-regular block text-xl mb-2 font-medium text-g1 dark:text-white">Song Link: <span class="dekko-regular text-o1 text-sm opacity-50">Paste the song's link below</span></label>
                                    <input type="url" name="song_name" id="id_song_name" placeholder="_________________________________________________________________" class="text-white placeholder-white placeholder:text-center placeholder:-translate-y-1 bg-p4 border-2 border-black focus:border-black focus:ring-black text-sm block w-full p-2.5" required />
                                </div>
{#                                <div class="flex justify-between">#}
{#                                    <div class="flex justify-center">#}
{#                                    </div>#}
{#                                </div>#}
                                <div class="flex justify-center">

                                    <button type="submit" class="text-g1 m-auto bg-p4 border-2 border-g1 hover:bg-p3 focus:ring-2 focus:outline-none focus:ring-g1 font-medium text-sm px-5 py-2.5 text-center">Add Name</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{#    {% if guest.id == admin.room_id %}#}
{##}
{#        <p class="text-white">Success!</p>#}
{##}
{#    {% else %}#}
{##}
{#        <div class="">#}
{#            <label for="guest_id" class="dokdo-regular block text-3xl mb-2 font-medium text-g1 dark:text-white">Room ID:<span class="dekko-regular text-o1 text-sm opacity-75"> Ask the host.</span></label>#}
{#            <input type="text" name="name" id="guest_id" placeholder="------" class="text-white text-center text-2xl placeholder-white placeholder:text-center placeholder:text-xl bg-p4 border-2 border-black focus:placeholder-opacity-0 focus:border-black focus:ring-black block w-full" maxlength="6" required />#}
{#        </div>#}
{##}
{#        <div class="dokdo-regular flex justify-center my-4 pt-6">#}
{#            <button type="submit" onClick={{ quest_id =  }} class="text-g1 m-auto bg-p4 border-2 border-g1 hover:bg-p3 focus:ring-2 focus:outline-none focus:ring-g1 font-light text-3xl p-5 text-center">Let's Party</button>#}
{#        </div>#}
{##}
{#    {% endif %}#}



{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load static %}


{% block content %}

    <div class="flex justify-center m-4">
      <!-- Top image -->
      <img class="w-6/12 h-auto m-4 pr-5" src="{% static 'images/partyatyourdoorimage_new.png' %}" alt="Party At Your Door">
    </div>

    <div class="px-10">

        <form id="roomIdForm" method="post">

            {% csrf_token %}
{#            {{ form.room_id }}#}
            <div>
                <label for="id_room_id" class="dokdo-regular block text-3xl mb-2 font-medium text-g1 dark:text-white">Room ID:<span class="dekko-regular text-o1 text-sm opacity-75"> Ask the host.</span></label>
                <input type="text" name="room_id" id="id_room_id" placeholder="------" class="text-white text-center text-2xl placeholder-white placeholder:text-center placeholder:text-xl bg-gradient-to-b from-p2 to-p1 border-2 border-black focus:placeholder-opacity-0 focus:border-black focus:ring-black block w-full" maxlength="6" required />
            </div>

            {% if form.errors %}
                <div class="error">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <p class="text-red-500">{{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <p class="text-red-500">{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}

            <h3 class="dokdo-regular text-3xl font-semibold text-g1 pt-3.5">
                Contact Info:<span class="dekko-regular text-o1 text-sm opacity-75"> Stay connected.</span>
            </h3>

            {#first last name div#}
            <div class="flex justify-between">
                <div class="">
                    <label for="id_first_name" class="dokdo-regular block text-xl mb-2 font-medium text-g1 dark:text-white"></label>
                    <input required type="text" name="first_name" id="id_first_name" placeholder="First Name:" class="text-white text-center placeholder-white placeholder:text-center bg-gradient-to-b from-p2 to-p1 border-2 border-black focus:placeholder-opacity-0 focus:border-black focus:ring-black text-sm block w-full p-2.5"/>
                </div>

                <div class="">
                    <label for="id_last_name" class="dokdo-regular block text-xl mb-2 font-medium text-g1 dark:text-white"></label>
                    <input type="text" name="last_name" id="id_last_name" placeholder="Last Name:" class="text-white text-center placeholder-white placeholder:text-center bg-gradient-to-b from-p2 to-p1 border-2 border-black focus:placeholder-opacity-0 focus:border-black focus:ring-black text-sm block w-full p-2.5"/>
                </div>
            </div>

            {#point of contact#}
            {{ form.social_types }}
{#            <div class="">#}
{#                <label for="id_social_types" class="dokdo-regular block text-xl mb-2 font-medium text-g1 dark:text-white"></label>#}
{#                <select name="social_types" id="id_social_types" class="text-white text-center bg-p4 border-2 border-black focus:border-black focus:ring-black text-sm block w-full p-2.5">#}
{#                    <option value="" disabled selected>--Choose a social contact option--</option>#}
{#                {% for social_type in contactinfo.social_type_choices %}#}
{#                    {% with social_type=social_types %}#}
{#                        <option value="{{ social_type }}">{{ social_type }}</option>#}
{#                    {% endwith %}#}
{#                {% endfor %}#}
    {#                <option value="tiktok">TikTok</option>#}
    {#                <option value="instagram">Instagram</option>#}
    {#                <option value="phone_number">Phone #</option>#}
    {#                <option value="email">Email</option>#}
{#                </select>#}
{#            </div>#}

            {#contact username#}
            <div>
                <label for="id_social_contact" class="dokdo-regular block text-xl mb-2 font-medium text-g1 dark:text-white"></label>
                <input required type="text" name="social_contact" id="id_social_contact" placeholder="--Type here" class="text-white placeholder-white placeholder:text-center focus:placeholder-opacity-0 bg-gradient-to-b from-p2 to-p1 border-2 border-black focus:border-black focus:ring-black text-sm block w-full p-2.5"/>
            </div>

            <div class="dokdo-regular flex justify-center my-4 pt-6">
                <button type="submit" class="text-g1 m-auto bg-p4 border-2 border-g1 hover:bg-p3 focus:ring-2 focus:outline-none focus:ring-g1 font-light text-3xl p-5 text-center">Let's Party</button>
            </div>
        </form>

        <p class="text-xs text-gray-500 pt-4">
            Disclaimer : All information collected will solely be used for Party At Your Door and will not be shared with third party vendors.
        </p>
    </div>

{% endblock %}

{#{% block script %}#}
{#    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>#}
{#    <script>#}
{#        $(document).ready(function() {#}
{#            $('#roomIdForm').on('submit', function(event) {#}
{#                event.preventDefault(); // Prevent the default form submission#}
{##}
{#                $.ajax({#}
{#                    url: $(this).attr('action'), // Use the form's action attribute#}
{#                    method: 'POST',#}
{#                    data: $(this).serialize(), // Serialize the form data#}
{#                    success: function(response) {#}
{#                        // Handle success (redirect or show success message)#}
{#                        window.location.href = response.redirect_url; // Change to your success behavior#}
{#                    },#}
{#                    error: function(xhr) {#}
{#                        // Handle errors#}
{#                        var errors = xhr.responseJSON.errors;#}
{#                        $('#roomIdError').html(''); // Clear previous errors#}
{#                        if (errors.room_id) {#}
{#                            $('#roomIdError').html(errors.room_id.join('<br>')); // Show errors under the field#}
{#                        }#}
{#                    }#}
{#                });#}
{#            });#}
{#        });#}
{#    </script>#}
{##}
{#{% endblock %}#}

templates/singer_queue.html
{% extends 'base.html' %}
{% load static %}


{# MAIN #}
{% block content %}

    <div class="mt-8 flex flex-col items-center">
        <section class="bg-white/10 w-11/12 flex flex-col border-2 border-p4">
            <h2 class="h-5 dokdo-regular text-g1 text-3xl text-center">How to sign-up</h2>
            <ol class="text-white m-auto space-y-0.5 p-3 text-sm">
                <li><span class="text-g1">1. Find your song</span> on <a href="https://www.youtube.com/results?search_query=karaoke&sp=mAEA" class="text-o1 underline">YouTube</a></li>
                <li><span class="text-g1">2. Copy the link</span> from the YouTube page.</li>
                <li><span class="text-g1">3. Tap ‘Add Name’ and paste</span> the song link.</li>
            </ol>
        </section>

        <div class="flex justify-center items-center w-full p-4">
          <!-- Image -->
          <img class="w-1/2 h-auto" src="{% static 'images/partyatyourdoorimage_new.png' %}" alt="Party At Your Door">

          <!-- Sign-up Button -->
          <button data-modal-target="authentication-modal" data-modal-toggle="authentication-modal"
                  class="dokdo-regular h-auto w-auto border-2 border-g1 bg-p1 text-2xl text-g1 p-4 mx-4 whitespace-nowrap" type="button">
              ADD NAME
          </button>

        </div>

        <div class="w-full flex flex-col items-center space-y-5">

            {#    Song Queue    #}
            <section class="w-11/12 flex flex-col items-center justify-around border-2 border-green-400 bg-gradient-to-b from-p1 to-p2 drop-shadow-lg">

                <p class="dokdo-regular text-center text-4xl text-g1">SONG QUEUE</p>
                <div class="w-full flex flex-col bg-gradient-to-b from-p1 to-p2 mx-24 px-5 pb-5 space-y-2">

                    {# queue of users place, name, song #}
                    <div class="bg-black border-2 border-g1 p-3 rounded">
                        <div class="flex justify-between text-o1 bg-black">
                            <span class="dokdo-regular basis-1/12">#</span>
                            <span class="dokdo-regular basis-1/3">Stage Name</span>
                            <span class="dokdo-regular basis-1/2">Song Name</span>
                        </div>
                            <div class="h-32 overflow-y-auto flex flex-col space-y-2">
                                {% for singer in singers %}
                                    {% if forloop.counter == 1 %}
                                        <div class="flex justify-between bg-g1 text-p1">
                                            <div class="w-full flex justify-between">
                                                <span class="dokdo-regular basis-1/12">{{ forloop.counter }}</span>
                                                <p class="basis-1/3">{{ singer.name }}</p>
                                                <span class="basis-1/2 truncate">{{ singer.song_name }}</span>
                                            </div>
                                        </div>
                                    {% else %}
                                        <div class="flex justify-between bg-p1 text-o1">
                                            <div class="w-full flex justify-between">
                                                <span class="dokdo-regular basis-1/12">{{ forloop.counter }}</span>
                                                <p class="basis-1/3">{{ singer.name }}</p>
                                                <span class="basis-1/2">{{ singer.song_name }}</span>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                    </div>

                </div>

            </section>



            <!-- Main modal -->
            <div id="authentication-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative p-4 w-full max-w-md max-h-full">
                    <!-- Modal content -->
                    <div class="relative bg-black border-2 border-p4 shadow">
                        <!-- Modal header -->
                        <div class="flex items-center justify-aroundx p-4 md:p-5 rounded-t">
                            <h3 class="dokdo-regular text-3xl font-semibold text-g1">
                                Sign Me Up!
                            </h3>


                            <button type="button" class="end-2.5 opacity-50 hover:opacity-100 focus:border-g1 bg-transparent text-xs ms-auto items-center" data-modal-hide="authentication-modal">
                                <svg class="text-g1 w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"></path>
                                </svg>
                                <span class="sr-only">Close modal</span>
                            </button>
                        </div>
                        <!-- Modal body -->
                        <div class="p-4 md:p-5">
                            <form method="post" class="space-y-4" action="#">
                                {% csrf_token %}
                                <div>
                                    <label for="id_name" class="dokdo-regular block text-xl mb-2 font-medium text-g1 dark:text-white">Name: <span class="dekko-regular text-o1 text-sm opacity-50">Get creative & pick your stage name</span></label>
                                    <input type="text" name="name" id="id_name" placeholder="_________________________________________________________________" class="text-white placeholder-white placeholder:text-center placeholder:-translate-y-1 bg-p4 border-2 border-black focus:border-black focus:ring-black text-sm block w-full p-2.5" required />
                                </div>
                                <div>
                                    <label for="id_song_name" class="dokdo-regular block text-xl mb-2 font-medium text-g1 dark:text-white">Song Name: <span class="dekko-regular text-o1 text-sm opacity-50">Title of your song</span></label>
                                    <input type="text" name="song_name" id="id_song_name" placeholder="_________________________________________________________________" class="text-white placeholder-white placeholder:text-center placeholder:-translate-y-1 bg-p4 border-2 border-black focus:border-black focus:ring-black text-sm block w-full p-2.5" required />
                                </div>
                                <div>
                                    <label for="id_song_link" class="dokdo-regular block text-xl mb-2 font-medium text-g1 dark:text-white">Song Link: <span class="dekko-regular text-o1 text-sm opacity-50">Paste the song's link below</span></label>
                                    <input type="url" name="song_link" id="id_song_link" placeholder="_________________________________________________________________" class="text-white placeholder-white placeholder:text-center placeholder:-translate-y-1 bg-p4 border-2 border-black focus:border-black focus:ring-black text-sm block w-full p-2.5" required />
                                </div>
                                <div class="flex justify-center">

                                    <button type="submit" class="text-g1 m-auto bg-p4 border-2 border-g1 hover:bg-p3 focus:ring-2 focus:outline-none focus:ring-g1 font-medium text-sm px-5 py-2.5 text-center">Add Name</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}